# Generated by Django 4.2.9 on 2024-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_CWE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe_id', models.IntegerField(unique=True)),
                ('cwe_name', models.CharField(blank=True, max_length=255)),
                ('cwe_description', models.TextField(blank=True)),
            ],
        ),
    ]
