# Generated by Django 4.2.9 on 2024-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_db_cwe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_OWASP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owasp_id', models.IntegerField(unique=True)),
                ('owasp_year', models.IntegerField()),
                ('owasp_name', models.CharField(blank=True, max_length=255)),
                ('owasp_description', models.TextField(blank=True)),
                ('owasp_url', models.CharField(blank=True, max_length=255)),
                ('owasp_full_id', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'OWASPs',
            },
        ),
        migrations.AlterModelOptions(
            name='db_cwe',
            options={'verbose_name_plural': 'CWEs'},
        ),
    ]
