# Generated by Django 4.2.9 on 2024-01-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_customer_report_finding_closed_at_finding_cwe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvss_vector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='finding',
            name='impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='poc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporting.report'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
