# Generated by Django 4.2.9 on 2024-01-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_finding_cvss_vector_finding_impact_finding_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='finding_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
