# Generated by Django 4.2.9 on 2024-01-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
