# Generated by Django 4.2.9 on 2024-02-07 00:04

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_alter_report_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='executive_summary_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='owasp_categories_summary_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='impact',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='location',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='poc',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='recommendation',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='references',
            field=martor.models.MartorField(blank=True),
        ),
    ]
