# Generated by Django 4.2.9 on 2024-02-07 17:56

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_report_executive_summary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_owasp',
            name='owasp_description',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='executive_summary',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='methodology',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='outofscope',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='recommendation',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='scope',
            field=martor.models.MartorField(blank=True),
        ),
    ]
