# Generated by Django 4.2.9 on 2024-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_remove_userprofile_role_userprofile_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='', max_length=9),
        ),
    ]
