# Generated by Django 4.2.9 on 2024-02-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0017_userprofile_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
