# Generated by Django 4.2.9 on 2024-02-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_userprofile_character_spacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='line_height',
            field=models.FloatField(default=1.5),
        ),
    ]
