# Generated by Django 4.2.9 on 2024-03-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_userprofile_line_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding_template',
            name='finding_id',
        ),
    ]
