# Generated by Django 4.2.9 on 2024-03-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_remove_finding_template_finding_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding_template',
            name='location',
        ),
        migrations.RemoveField(
            model_name='finding_template',
            name='poc',
        ),
    ]
