# Generated by Django 4.2.9 on 2024-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_remove_finding_template_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='nmap_scan',
            field=models.TextField(default='', help_text='Nmap scan results in JSON format'),
        ),
    ]
