# Generated by Django 4.2.9 on 2024-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_report_nmap_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='openvas_scan',
            field=models.TextField(default='', help_text='OpenVAS scan results in JSON format'),
        ),
    ]
