# Generated by Django 4.2.9 on 2024-03-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0026_appendix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
