# Generated by Django 4.2.9 on 2024-03-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0027_alter_userprofile_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='finding_template',
            name='impact',
        ),
    ]
