# Generated by Django 4.2.9 on 2024-03-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0028_remove_finding_impact_remove_finding_template_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding_template',
            name='cwe',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.db_cwe'),
        ),
        migrations.AlterField(
            model_name='finding_template',
            name='cvss_vector',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='finding_template',
            name='owasp',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.db_owasp'),
        ),
    ]
