# Generated by Django 4.2.9 on 2024-03-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0029_finding_template_cwe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding_template',
            name='cwe',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.db_cwe'),
        ),
        migrations.AlterField(
            model_name='finding_template',
            name='owasp',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.db_owasp'),
        ),
    ]
