# Generated by Django 4.2.9 on 2024-03-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_alter_finding_template_cwe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=2048)),
                ('generation_date', models.DateTimeField()),
                ('filetype', models.CharField(max_length=32)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.report')),
            ],
            options={
                'verbose_name_plural': 'Deliverables',
            },
        ),
    ]
